name: Bearer
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pwd
        run: |
           echo "Current directory: $(pwd)"
           curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh -s -- -b /usr/local/bin
           sudo apt-get install -y apt-transport-https
           echo "deb [trusted=yes] https://apt.fury.io/bearer/ /" | sudo tee -a /etc/apt/sources.list.d/fury.list
           sudo apt-get update
           sudo apt-get install -y bearer
           bearer scan /home/runner/work/fullstack-bank --scanner=sast .
