name: Bearer
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pwd
        run: |
           echo "Current directory: $(pwd)"
      - name: Bearer
        continue-on-error: true
        uses: bearer/bearer-action@v2
        with:
          format: sarif
          output: /home/runner/work/fullstack-bank/fullstack-bank/results.sarif
