name: dastardly

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  webapp-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          echo "Current directory: $(pwd)"

      - name: Run Dastardly Action Step
        continue-on-error: true
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://www.gytworkz.com/'
          
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'
          require_tests: true    
