name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs: 
  build1:
    runs-on: ubuntu-latest
    outputs:
      exitCode: ${{ steps.set-exit-code.outputs.exitCode }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set default exit code
        id: set-exit-code
        run: echo "exitCode=0" >>$GITHUB_ENV

      - name: Build the Docker image
        run: |
          if docker build . --file Dockerfile --tag my-image-name:$(date +%s); then
            echo "Build successful"
          else
            echo "Build failed"
            echo "exitCode=1" >>$GITHUB_ENV
            exit 1
          fi
          
      - name: Send email on failure (chatbotclient)
        if: ${{ env.exitCode }} != '0'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Build Failed: Chatbot Client'
          body: 'The build for Chatbot Client failed in the GitHub Action workflow.'
          to: 'haritha.guduru@gytworkz.com'
          from: 'santosh.chintapally@gytworkz.com'

  build2:
    runs-on: ubuntu-latest
    outputs:
      exitCode: ${{ steps.set-exit-code.outputs.exitCode }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set default exit code
        id: set-exit-code
        run: echo "exitCode=0" >>$GITHUB_ENV

      - name: Build Hello World
        run: |
          if echo Hello, world!; then
            echo "Build successful"
          else
            echo "Build failed"
            echo "exitCode=1" >>$GITHUB_ENV
            exit 1
          fi
          
      - name: Send email on failure (chatbotclient)
        if: ${{ env.exitCode }} != '0'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Build Failed: Chatbot Client'
          body: 'The build for Chatbot Client failed in the GitHub Action workflow.'
          to: 'haritha.guduru@gytworkz.com'
          from: 'santosh.chintapally@gytworkz.com'   
