name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        id: build
        run: |
          docker buil . --file Dockerfile --tag my-image-name:$(date +%s) || echo "::set-output name=exitCode::1"

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check if the build failed
        id: check-build-status
        run: exit ${{ needs.build.outputs.exitCode || 0 }}
      - name: Send email
        if: steps.check-build-status.outputs.exitCode != 0
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'GitHub Action Email - Build Failed'
          body: 'The build failed in the GitHub Action workflow.'
          to: 'haritha.guduru@gytworkz.com'
          from: 'santosh.chintapally@gytworkz.com'
