name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Check if build failed
      id: check_build
      run: echo "::set-output name=failed::$(docker inspect -f '{{.State.ExitCode}}' $(docker ps -lq))"

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: build
    if: steps.build.outputs.failed == '1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send email on failure
        run: |
          # Use a command to send an email here, for example, using a SMTP server or SendGrid API.
          # This is just a placeholder, replace it with the actual command to send an email.
          echo "Build failed. Sending email..."
