name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker buil . --file Dockerfile --tag my-image-name:$(date +%s)

  notify-on-failure:
    runs-on: ubuntu-latest
    if: failure()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'GitHub Action Email'
          body: 'This email is sent from a GitHub Action workflow.'
          to: 'haritha.guduru@gytworkz.com'
          from: 'santosh.chintapally@gytworkz.com'
