name: Email and docker

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:   

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set default exit code for build1
        id: set-exit-code1
        run: |
          if docker build . --file Dockerfile --tag my-image-name:$(date +%s); then
            echo "Build successful for build1"
          else
            echo "Build failed for build1"
            echo "exitCodeBuild1=1" >> $GITHUB_OUTPUT ## CHANGE ##
            exit 1
          fi

      - name: Send email on failure (build1)
        if:  steps.set-exit-code1.outputs.exitCodeBuild1 == '1' && !cancelled() ## Improvment ##
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Build Failed: build1'
          body: 'The build for build1 failed in the GitHub Action workflow.'
          to: 'haritha.guduru@gytworkz.com'
          from: 'haritha.guduru@gytworkz.com'

  build2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set default exit code for build1
        id: set-exit-code2
        run: |
          if echo Hello, world!; then
            echo "Build successful for build2"
          else
            echo "Build failed for build2"
            echo "exitCodeBuild2=1" >> $GITHUB_OUTPUT ## CHANGE ##
            exit 1
          fi

      - name: Send email on failure (build1)
        if:  steps.set-exit-code2.outputs.exitCodeBuild2 == '1' && !cancelled() ## Improvment ##
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Build Failed: build2'
          body: 'The build for build1 failed in the GitHub Action workflow.'
          to: 'haritha.guduru@gytworkz.com'
          from: 'haritha.guduru@gytworkz.com'
   
