name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs: 
  build:
    runs-on: ubuntu-latest
    outputs:
      exitCode: ${{ steps.set-exit-code.outputs.exitCode }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set default exit code
        id: set-exit-code
        run: echo "::set-output name=exitCode::0"

      - name: Build the Docker image
        run: |
          if docker build . --file Dockerfile --tag my-image-name:$(date +%s); then
            echo "Build successful"
          else
            echo "Build failed"
            echo "::set-output name=exitCode::1"
            exit 1
          fi

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'GitHub Action Email - Build Failed'
          body: 'The build failed in the GitHub Action workflow.'
          to: 'haritha.guduru@gytworkz.com'
          from: 'santosh.chintapally@gytworkz.com'
