name: Email and docker

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs: 
  build1:
    runs-on: ubuntu-latest
    outputs:
      exitCodeBuild1: ${{ steps.set-exit-code1.outputs.exitCode }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set default exit code for build1
        id: set-exit-code1
        run: echo "exitCodeBuild1=0" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          if docker build . --file Dockerfile --tag my-image-name:$(date +%s); then
            echo "Build successful for build1"
          else
            echo "Build failed for build1"
            echo "exitCodeBuild1=1" >> $GITHUB_ENV
            exit 1
          fi
          
      - name: Send email on failure (build1)
        if: ${{ needs.build1.outputs.exitCodeBuild1 == '1' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Build Failed: build1'
          body: 'The build for build1 failed in the GitHub Action workflow.'
          to: 'haritha.guduru@gytworkz.com'
          from: 'santosh.chintapally@gytworkz.com'

  build2:
    runs-on: ubuntu-latest
    outputs:
      exitCodeBuild2: ${{ steps.set-exit-code2.outputs.exitCode }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set default exit code for build2
        id: set-exit-code2
        run: echo "exitCodeBuild2=0" >> $GITHUB_ENV

      - name: Build Hello World
        run: |
          if echo Hello, world!; then
            echo "Build successful for build2"
          else
            echo "Build failed for build2"
            echo "exitCodeBuild2=1" >> $GITHUB_ENV
            exit 1
          fi
          
      - name: Send email on failure (build2)
        if: ${{ needs.build2.outputs.exitCodeBuild2 == '1' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Build Failed: build2'
          body: 'The build for build2 failed in the GitHub Action workflow.'
          to: 'haritha.guduru@gytworkz.com'
          from: 'santosh.chintapally@gytworkz.com'
