name: Send Email on Failure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build the project
        run: ./build.sh

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test the project
        run: ./test.sh

  send-email:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'GitHub Action Email'
          body: 'One of the jobs in the workflow failed.'
          to: 'haritha.guduru@gytworkz.com'
          from: 'santosh.chintapally@gytworkz.com'
