name: Publish Release

on:
  push:
    branches: [main]
    tags:
      - v*
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build release
        run: make build

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag: ${{ github.ref }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.create_release.upload_url }}
          asset_path: ./build/my_app.zip

      - name: Publish release
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.inputs.create_release.id }} \
            -d '{
              "draft": false
            }'
