on:
  push:
    branches:
      - main
  workflow_dispatch: 
 
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Conventional changelog action
        id: changelog
        uses: TriPSs/conventional-changelog-action@latest
        with:
          github-token: "${{ secrets.TOKEN }}"
      - name: Get latest tag
        id: get-latest-tag
        run: echo "::set-output name=latest_tag::$(git describe --tags --abbrev=0)"
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false'}}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: false
      - name: Tag code if necessary
        run: |
          if [[ "${{ steps.changelog.outputs.tag }}" != "${{ steps.get-latest-tag.outputs.latest_tag }}" ]]; then
            git tag -a ${{ steps.changelog.outputs.tag }} -m "Release ${{ steps.changelog.outputs.tag }}"
            git push origin ${{ steps.changelog.outputs.tag }}
          fi
