name: Slack2 and SAST

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Print branch name
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Build Docker Image
        run: |
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Run Static Code Analysis and Security Scan
        run: |
          # Run SAST scan for TypeScript, CSS, SCSS, and JavaScript
          echo "Running Static Code Analysis and Security Scan..."
          # Command to run your specific SAST tool for TypeScript, CSS, SCSS, JavaScript

  build3:
    runs-on: ubuntu-latest
    steps:
      - name: Self sast-scan
        uses: AppThreat/sast-scan-action@v1.0.0
        with:
          output: reports
          type: "typescript,css,scss,javascript"

      - name: Upload scan reports
        uses: actions/upload-artifact@v2
        with:
          name: sast-scan-reports
          path: reports

  slack-workflow-status:
    if: always()
    needs:
      - build1
      - build2
      - build3
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: '#app'
          name: 'hari'
