name: Docker and Hello world

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  
jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Hello World Script
        run: |
          echo Hello world!
          
  build3:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
         files: |
           test-results/**/*.xml
           test-results/**/*.trx
           test-results/**/*.json
          
  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - build1
      - build2
      - build3
    runs-on: ubuntu-latest
    permissions:
      actions: 'read'
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.TOKEN }} # GitHub automatically creates a GITHUB_TOKEN secret for you.
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: '#app'
          name: 'hari'
