name: Hello world and Docker

on:
  push:
    branches:
      - "main"
  workflow_dispatch:    

jobs:
  build1:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          status: starting
          channel: '#app'
          message: Starting Docker Build
        if: always()
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
       
      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#app'
          message: Build1 ${{env.GITHUB_REF_NAME}}
        if: always()

  build2:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          status: starting
          channel: '#app'
          message: Starting Hello World
        if: always()
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Starting Hello World
        run: |
          echo Hello world!
       
      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#app'
          message: Build2 ${{env.GITHUB_REF_NAME}}
        if: always()
