name: Email and docker

on:
  push:
    branches:
      - "main"

jobs:
  build1:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          status: starting
          channel: '#app'
          message: Starting Build and Deploy...
        if: always()
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          echo Hello world!
       
      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#app'
          message: Build ${{env.GITHUB_REF_NAME}}
        if: always()

  build2:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          status: starting
          channel: '#app'
          message: Starting Build and Deploy...
        if: always()
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          echo Hello world!
       
      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#app'
          message: Build ${{env.GITHUB_REF_NAME}}
        if: always()
