on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud Scan
        run: |
          /usr/local/bin/sonar-scanner \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=SONAR_TOKEN \
            -Dsonar.projectName=Bank \
            -Dsonar.projectKey=Bank \
            -Dsonar.sources=lib/ # Specify the path to your source code directory
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Set the SONAR_TOKEN environment variable using GitHub secret

    
