name: sonar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectName=Bank \
            -Dsonar.projectKey=Bank
        env:
          SCANNER_HOME: SCANNER_HOME/bin/sonar-scanner # Update this with the actual path to your SonarScanner installation

      # Add additional steps as needed
