name: MS-Teams and Experiment2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Starting Hello World
        run: |
          echo Hello world!

  Teams-workflow-status:
    if: always() 
    name: output
    needs:
      - build1
      - build2
    runs-on: ubuntu-latest
    permissions:
      actions: 'read'
    steps:
      - name: Notify Teams Build Status
        uses: hunghg255/action-notifications@master
        with:
          ms_teams_webhook: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: Build Status
