name: MS-Teams

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
          
      - name: Set job status
        id: set_status
        run: echo "::set-output name=job_status::success"
        if: ${{ success() }}
        
  build2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Starting Hello World
        run: |
          echo Hello world!

      - name: Set job status
        id: set_status
        run: echo "::set-output name=job_status::success"
        if: ${{ success() }}     

  teams_notification:
    if: always()
    needs:
      - build1
      - build2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Teams Workflow Notification
        uses: opsless/ms-teams-github-actions@main
        with:
          github-token: ${{ secrets.TOKEN }}
          webhook: ${{ secrets.TEAMS_WEBHOOK_URL }}
          status: |
            ${{ (needs.build1.outputs.job_status == 'success' && needs.build2.outputs.job_status == 'success') && 'Success: All jobs completed successfully' || 'Failure: One or more jobs failed' }}
