name: MS-Teams and Experiment2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build1:
    runs-on: ubuntu-latest
    outputs:
      # Define an output variable to store the status of build1
      id: build1
      value: ${{ job.status }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build2:
    runs-on: ubuntu-latest
    outputs:
      # Define an output variable to store the status of build2
      id: build2
      value: ${{ job.status }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Starting Hello World
        run: |
          echo Hello world!

  Teams-workflow-status:
    runs-on: ubuntu-latest
    needs:
      - build1
      - build2
    steps:
      - name: Notify Teams Build Status
        uses: hunghg255/action-notifications@master
        with:
          ms_teams_webhook: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: Build Status
          text: |
            Build 1 Status: ${{ needs.build1.outputs.value }}
            Build 2 Status: ${{ needs.build2.outputs.value }}
