name: MS-Teams

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
          
      - name: Set job status
        id: set_status
        run: echo "::set-output name=job1_status::${{ job.status }}"
      
      - name: Notify Teams Build Status
        uses: neonidian/teams-notify-build-status@v3
        if: always()
        with:
          webhookUrl: ${{ secrets.TEAMS_WEBHOOK_URL }}
          message: Workflow has been run
          titleBackgroundColor: ${{ job.status }}
          Text: Workflow is ${{ steps.<step_id>.outcome }}
        env:
          SHOULD_DISPLAY_VIEW_RUN_BUTTON: true
          SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true
          SHOULD_DISPLAY_ACTOR_LABEL: true

  build2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Starting Hello World
        run: |
          echo Hello world!
      - name: Set job status
        id: set_status
        run: echo "::set-output name=job2_status::${{ job.status }}"

      - name: Notify Teams Build Status
        uses: neonidian/teams-notify-build-status@v3
        if: always()
        with:
          webhookUrl: ${{ secrets.TEAMS_WEBHOOK_URL }}
          message: Workflow has been run
          titleBackgroundColor: ${{ job.status }}
          Text: Workflow is ${{ steps.<step_id>.outcome }}
        env:
          SHOULD_DISPLAY_VIEW_RUN_BUTTON: true
          SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true
          SHOULD_DISPLAY_ACTOR_LABEL: true
